## 比较 Coxeter 矩阵

In [2]:
# 转化 gap 字符串
gap_str = lambda s:gap('"'+s+'"')

# 导入自编函数
gap.Read(gap_str("big_weyl_group.py"))

LieThetas = gap("LieThetas")

In [3]:
def OrderMatrix(gens):
    """计算 gens 的群阶矩阵"""
    orders = [[gap.Order(a*b) for a in gens] for b in gens]
    return matrix(ZZ,orders)

In [2]:
a = identity_matrix(3)

In [3]:
a

[1 0 0]
[0 1 0]
[0 0 1]

In [4]:
e^a

[e 0 0]
[0 e 0]
[0 0 e]

In [4]:
s = "A"
n = 2

# Weyl 群的群阶矩阵
weyl_group = WeylGroup([s,n])
print(weyl_group.coxeter_matrix())
print()

# Weyl 群扩张群的群阶矩阵
thetas = LieThetas(gap_str(s),n) # 生成元
print(OrderMatrix(thetas))

[1 3]
[3 1]

[2 3]
[3 2]


### 其他型

In [ ]:
n = 6
for s in "ABCDE":
    print(s)
#     weyl_group = WeylGroup([s,n])
#     print(weyl_group.coxeter_matrix(),"\n")
    thetas = LieThetas(gap_str(s),n)
    print(OrderMatrix(thetas))

In [ ]:
n = 3
thetas = LieThetas(gap_str("B"),n)
print(OrderMatrix(thetas),"\n")
thetas = LieThetas(gap_str("C"),n)
print(OrderMatrix(thetas))

## 泛性质

In [2]:
# 转化 gap 字符串
gap_str = lambda s:gap('"'+s+'"')

# 导入自编函数
gap.Read(gap_str("big_weyl_group.py"))

### 群阶例子 

In [ ]:
# 定义矩阵群
F = GF(3)
gens = [matrix(F,[[1,1,0],
                 [0,1,0],
                 [0,0,1]]),
        matrix(F,[[1,0,0],
                  [0,1,1],
                  [0,0,1]]),
        matrix(F,[[1,0,1],
                  [0,1,0],
                  [0,0,1]])]
G = MatrixGroup(gens)
# 群阶和交换性
print(len(G),G.is_abelian())
for a in G:
    print(a.order(),end="\t")
print()
# 定义交换群
AG = AbelianGroup(3,[3,3,3])
print(len(AG),AG.is_abelian())
for a in AG:
    print(a.order(),end="\t")

In [ ]:
OrderMatrix(gens)

In [ ]:
AG_gens = AG.gens()
orders = [[(a*b).order() for a in AG_gens] for b in AG_gens]
matrix(ZZ,orders)

### 自由群

In [1]:
def GroupByOrderMatrix(n,mat):
    """群阶矩阵 -> 自由群商群"""
    FG = FreeGroup(n) # 自由群
    gens = FG.gens() # 生成元
    # 生成关系
    relations = [(gens[i]*gens[j])^mat[i,j] for i in range(n) for j in range(n)]
    return FG/relations

In [3]:
# Coxeter 群
mat = matrix(CoxeterMatrix(["A",3]))
G_A3 = GroupByOrderMatrix(3,mat)
for a in G_A3:
    print(a,end="\t")

1	x0	x2	x0*x2	x1	x0*x1	x2*x1	x0*x2*x1	x1*x0	x0*x1*x0	x2*x1*x0	x0*x2*x1*x0	x1*x2	x1*x2*x1	x0*x1*x2	x0*x1*x2*x1	x1*x0*x2	x1*x2*x1*x0	x0*x1*x0*x2	x0*x1*x2*x1*x0	x1*x0*x2*x1	x1*x0*x2*x1*x0	x0*x1*x0*x2*x1	x0*x1*x0*x2*x1*x0	

In [4]:
# 三阶群-使用 GAP 函数
mat = 3 * matrix.ones(3)
G = gap.QuotientGroup(gap(mat))

### 检验泛性质

In [ ]:
# sagemath 有点拉啊，，，
s = "A"
n = 2
thetas = LieThetas(gap_str(s),n) # 生成元
mat = OrderMatrix(thetas)
G = GroupByOrderMatrix(n,mat)
len(G)

## 结构

In [ ]:
Lie = [["A",range(1,9)],["B",range(2,9)],["C",range(3,8)],["D",range(4,9)],
       ["E",range(6,7)],["F",[4]],["G",[2]]]
res = [['type','G的群阶','K的群阶','weyl群阶数','G/K阶数','K的结构']] 
dim = [['type\\rank']+[i+1 for i in range(8)]] #记录群阶
times = [['type\\rank']+[i+1 for i in range(8)]] #记录时间
for s,l in Lie:
    print(s,list(l))
    dim.append([s]+['-' for i in range(l[0]-1)])
    times.append([s]+['-' for i in range(l[0]-1)])
    for n in l:
        t = time.time()
        res.append([s+str(n)])
        thetas = LieThetas(gap_str(s),n) 
        G = gap.Group(thetas) #矩阵生成群
        K = gap.Group([x^2 for x in thetas]) #theta_i^2生成群
        W = WeylGroup([s,n])
        Gs = gap.Size(G) #G的阶数
        Ks = gap.Size(K) #K的阶数
        Ws = W.order() #weyl群的阶数
        GKs = gap.Size(G/K) #商群G/K的阶数
        K_st = gap.StructureDescription(K)
        res[-1].extend([Gs,Ks,Ws,GKs,str(K_st)])
        dim[-1].append(thetas[1].Length())
        times[-1].append("%.3f"%(time.time()-t))

In [ ]:
133,248
2903040
696729600

In [ ]:
table(res)

In [ ]:
table(dim)

In [ ]:
table(times)

In [ ]:
times

In [ ]:
def str2matrix(s):
    '''将字符串形式的矩阵转化为矩阵形式(貌似有误！)'''
    s = s.split('\n') #按行拆解
    mat = []
    for line in s:
        mat.append([int(i) for i in line.split()[1:-1]])
    return mat

In [ ]:
s = gap_str("A")
n = 2
for i in [1..n]:
    theta = gap.LieThetas(s,i)
    #G:=Group(theta);;
    K = gap.Group([x^2 for x in theta])
    a = gap.StructureDescription(K)
    #print(Size(G/K));